# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         WEC-HTTP
version:      0.01
version_from: 
installdirs:  site
requires:
    Email::Date:                   0
    Email::Simple:                 0
    Test::More:                    0.11
    URI:                           0
    WEC:                           0.01

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
